export enum ComponentCommands {
    SET_DEBUG_CHANNEL = "setdebugchannel",
    SET_HOURS = "sethours",
    SET_AUTO_REACT = "setautoreact",
    SET_BRUH = "setbruh",
    SET_DOTW = "setdotw",
    SET_STAR = "setstar",
    SET_VC_PAIRS = "setvcpairs",
    SET_REACT_PAIRS = "setreactpairs",
    DEBUG_MODE = "debug",
    SET_PREFIX = "prefix",
    EXPORT_CONFIG = "exportconfig",
    RESET_CONFIG = "resetconfig",
    B_SPEAK = "b",
    BRUH = "bruh",
    BRUH_RECACHE = "rebruh",
    CHEEMS = "cheems",
    HELP = "help",
    PING  = "ping",
    SAY = "say",
    SET_PNGRC = "setpngrc",
    SET_BANNER= "setbanner",
    ROTATE_BANNER= "rotatebanner",
    SET_MEDIA_CHANNEL= "setmc",
    GET_MEDIA_CHANNEL= "getmc",
    SET_DYNAMIC_VC= "setdynamicvc",
    SET_AUTO_THREAD= "setautothread"
}
