export enum CommandStrings {
    SET_HOURS = "sethours",
    SET_AUTO_REACT = "setautoreact",
    SET_BRUH = "setbruh",
    SET_DOTW = "setdotw",
    SET_VC_PAIRS = "setvcpairs",
    SET_REACT_PAIRS = "setreactpairs",
    REGISTER = "register",
    UNREGISTER = "unregister",
    DEV_MODE = "dev",
    SET_PREFIX = "prefix",
    EXPORT_CONFIG = "exportconfig",
    RESET_CONFIG = "resetconfig",
    B_SPEAK = "b",
    BRUH = "bruh",
    CHEEMS = "cheems",
    HELP = "help",
    PING  = "ping",
    SAY = "say"
}
